### ISSUE TITLE
postInstall causes npm to fail on Windows

### ISSUE THREAD

**Issue by aendra-rininsland** [isao/argg#1]
`cat` doesn't exist in Windows so npm exits with failure.

See: https://github.com/michael/github/pull/206#issuecomment-124120061

![Screenshot](http://i.imgur.com/SKNOuhp.png)

**Comment by isao** [comment]
Thanks @aendrew. FYI, `tape` has incorporated the functionality in `argg`, so if you are using `tape` you do not need this package any more.

I've removed the non-function `postinstall` directive. Thanks for the report!

**Comment by isao** [comment]
published 0.0.2 with the postinstall removal to npm. thanks again.

**Comment by aendra-rininsland** [comment]
@isao Ah! Didn't know that about Tape! Cool, thanks!
